---
- name: Automate Media Containers Update
  hosts: media
  gather_facts: false
  tasks:
    - name: Trigger the native community script update command
      ansible.builtin.shell: update
      environment:
        TERM: xterm-256color
      register: script_output

    - name: Stream the update results back to Semaphore
      ansible.builtin.debug:
        var: script_output.stdout_lines
